{% set name = "alphashape" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33d2bf4b7c4eeb413e071521d38535441f25218afc12a8804ac693d9e93bb94e

build:
  number: 0
  noarch: python
  entry_points:
    - alphashape=alphashape.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - click >=6.0
    - click-log >=0.3.2
    - python
    - scipy >=1.0.0
    - shapely >=1.4.0
    - geopandas >=0.6.2

test:
  imports:
    - alphashape
  commands:
    - alphashape --help

about:
  home: https://github.com/bellockk/alphashape
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Toolbox for generating alpha shapes.
  doc_url: https://alphashape.readthedocs.io/en/latest/
  dev_url: https://github.com/bellockk

extra:
  recipe-maintainers:
    - ngodber
