{% set name = "alphashape" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6993fe9da2753a3ce2c625f39b7dda495e462ae04cf1f29b67c81a8e15ca73b0

build:
  number: 0
  noarch: python
  entry_points:
    - alphashape=alphashape.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - click >=6.0
    - click-log >=0.3.2
    - python >=3.8
    - scipy >=1.0.0
    - shapely >=1.4.0
    - geopandas >=0.6.2
    - numpy >=1.6

test:
  imports:
    - alphashape
  commands:
    - alphashape --help

about:
  home: https://github.com/bellockk/alphashape
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Toolbox for generating alpha shapes.
  doc_url: https://alphashape.readthedocs.io/en/latest/
  dev_url: https://github.com/bellockk

extra:
  recipe-maintainers:
    - ngodber
    - bellockk
